name: torch-gpu
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy=1.23.5
  - opencv=4.5.3
  - matplotlib=3.6.2 
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.6.0
  - scipy=1.9.3
  - tqdm=4.64.1
  - kornia=0.6.9
  - tensorboard=2.11.0 #pip
  - thin-plate-spline=1.0.1 #pip