model_path: 'pretrained/aslfeat/model.ckpt-380000'
net:
  max_dim: 2048
  lr: 0.001
  config:
    kpt_n: 500
    kpt_refinement: true
    deform_desc: 1
    score_thld: 0.5
    edge_thld: 10
    multi_scale: false
    multi_level: true
    nms_size: 3
    eof_mask: 5
    need_norm: true
    use_peakiness: true
match:
  ratio_test: 0.8
  cross_check: true